### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by cody-carlson** [eaton-dev-workshops/github-games-jimlane#1]
When attempting to access this at https://eaton-dev-workshops.github.io/github-games-jimlane, I am getting a 404. This could be caused by a couple of things:

- GitHub Pages needs to be enabled on the  branch. You can fix this in the repository settings.
- The **index.html** file is incorrectly named **inde.html**. We will fix this together in class.

Can you fix the first bullet, please?

**Comment by jimlane** [comment]
Prior PR fixed these issues

**Comment by jimlane** [comment]
These issues were fixed with the prior PR
